### ISSUE TITLE
RITnet retraining problem

### ISSUE THREAD

**Issue by Leesisisi** [AayushKrChaudhary/RITnet#4]
Hello, this is Lee, I‘m very interested in the network you published. I now have the data set I collected and want to retrain on your network, but some problems occurred. I changed the instruction according to the name and path of my data set, but still reported an error:
Traceback (most recent call last):
  File "train.py", line 103, in <module>
    transform = transform, **kwargs)
  File "/home/mprl-et/leesisisi/RITnet-master/dataset.py", line 131, in __init__
    for file in os.listdir(osp.join(self.filepath,'images')):   
FileNotFoundError: [Errno 2] No such file or directory: 'RITnet_Self_Dataset/train/images'

I'm sure the filepath is right, and because of our picture format is jpg, I changed the dataset.py line132 and 133:
 for file in os.listdir(osp.join(self.filepath,'images')):   
            if file.endswith(".jpg"):
               listall.append(file.strip(".jpg"))

Will this cause any problems? Are there specific requirements for the data format of the training set? If so please let me know.

Thank you.

**Comment by AayushKrChaudhary** [comment]
That should fix the issue. Can you print and check if listall is empty or contains all the images you want?

**Comment by AayushKrChaudhary** [comment]
Is more of the folder arrangement issue rather than a code base issue. So closing this issue.

Folder should be arranged in Folder_name/train(test)/images/
If you are using '.jpg' change lines 132,133,148 of file dataset.py [Updated on Sept 19, 2019]
