### ISSUE TITLE
Hi, we are interested in your work, can you give me a OpenEDS dataset download link?

### ISSUE THREAD

**Issue by huaji98** [AayushKrChaudhary/RITnet#7]
We found no public download link for this dataset.

**Comment by Lukeskywalker147** [comment]
https://cs.rit.edu/~cgaplab/RIT-Eyes/

**Comment by huaji98** [comment]
> https://cs.rit.edu/~cgaplab/RIT-Eyes/

Thanks, But this format does not match the code?

**Comment by mixxen** [comment]
Looks like the data in the link is simulated eye data. Would it be possible to get access to the real Open Eye Dataset?

**Comment by AayushKrChaudhary** [comment]
We do not have the right to share the OpenEDS-2019. The dataset is from https://research.facebook.com/openeds-challenge/ 
Regarding RIT-Eyes the format of the file will image loading script has to be changed to load those images.

**Comment by perphyguo** [comment]
Thanks for your dataset!
After opening the .p file, I am confused about the details.
Is there some place for me to learn he exact meaning?
What I am doing is to locate pupil with normal camera, not in VR. So what is the data in 'pupil' mean? Seems it is not x, y coordinate in the picture.
Thanks!

![Capture](https://user-images.githubusercontent.com/14899779/220863035-a52d4432-31a0-4a85-861f-e1f56f76f3d8.PNG)

**Comment by lukelu520** [comment]
Hi @perphyguo , I was wondering how would you open these .p files. I have tried multiple apps but still can't make it.
Hope to hear your expertise. Thx. 

> Thanks for your dataset! After opening the .p file, I am confused about the details. Is there some place for me to learn he exact meaning? What I am doing is to locate pupil with normal camera, not in VR. So what is the data in 'pupil' mean? Seems it is not x, y coordinate in the picture. Thanks!
> 
> ![Capture](https://user-images.githubusercontent.com/14899779/220863035-a52d4432-31a0-4a85-861f-e1f56f76f3d8.PNG)

**Comment by perphyguo** [comment]
> Hi @perphyguo , I was wondering how would you open these .p files. I have tried multiple apps but still can't make it. Hope to hear your expertise. Thx.
> 
> > Thanks for your dataset! After opening the .p file, I am confused about the details. Is there some place for me to learn he exact meaning? What I am doing is to locate pupil with normal camera, not in VR. So what is the data in 'pupil' mean? Seems it is not x, y coordinate in the picture. Thanks!
> > ![Capture](https://user-images.githubusercontent.com/14899779/220863035-a52d4432-31a0-4a85-861f-e1f56f76f3d8.PNG)

I use a library to open .p file in python

**Comment by lukelu520** [comment]
@perphyguo thanks for your advice, we finally figured out the .p file is pickle file instead of matlab P-file :) !

**Comment by perphyguo** [comment]
> @perphyguo thanks for your advice, we finally figured out the .p file is pickle file instead of matlab P-file :) !

So would you tell me the meaning of the labels if you figure it out?

Thanks!

**Comment by lukelu312** [comment]
To my knowledge, labels are about segmented area for corresponding eye regions, or classification, (e.g. if eyeglasses exist), or camera geometric info, e.g. position.
Which label you'd like to know the most ?  
@perphyguo

**Comment by AayushKrChaudhary** [comment]
The pickle file you are reading is not the correct file for this model. 
The model only takes image as input and the label must be image with segmentation labels stored in numpy fashion. Using appropriate files may help to solve the issue

The OpenEDS dataset must be downloaded from the source owners [Me as the authors of this paper do not have legal right to share the dataset. 
Required format: Image as input 
                             Labels same size as input image but corresponding to the segmentation labels

**Comment by shivaz560** [comment]
Hello. Could you give me an example label folder for one of your synthetic datasets ?
