### ISSUE TITLE
Testing best_model on openEDS

### ISSUE THREAD

**Issue by AbdouMechraoui** [AayushKrChaudhary/RITnet#8]
Hi there,
Thank you so much for making the code available. I tried to test `best_model` on `OpenEDS` data, but the results don't look satisfying. I wanted to ask, what dataset was `best_model` trained on? Also, how well does `best_model` generalize to real-world data? I plan to use your model for eye segmentation of real-world images, and I was wondering if you can give me an insight on how well it performs, or what to look out for. 
Below I have attached some of the results I got when I tested on `OpenEDS`. Is there any way to improve the resulting segmentations? 

![0000](https://user-images.githubusercontent.com/52415829/141980071-ab9717b5-136c-48ab-9943-16bdd1d59fc3.jpg)
![0006](https://user-images.githubusercontent.com/52415829/141980100-c43f3f54-5cd5-4c86-9b2f-099ba7680fe9.jpg)

**Comment by AayushKrChaudhary** [comment]
The images are not from OpenEDS-2019. The best model is trained on real images of OpenEDS-2019. Retraining the model in this dataset will help improve the result.
